"""add ippool tables for ip management

Revision ID: 191cd2b28b8b
Revises: 413818ea977d
Create Date: 2026-02-02 21:59:04.404229

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "191cd2b28b8b"
down_revision: Union[str, Sequence[str], None] = "413818ea977d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ip_pools",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "network", sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False
        ),
        sa.Column("cidr", sqlmodel.sql.sqltypes.AutoString(length=18), nullable=False),
        sa.Column(
            "gateway", sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False
        ),
        sa.Column(
            "start_ip", sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False
        ),
        sa.Column(
            "end_ip", sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ip_pools_is_active"), "ip_pools", ["is_active"], unique=False
    )
    op.create_index(op.f("ix_ip_pools_name"), "ip_pools", ["name"], unique=True)
    op.create_table(
        "ip_allocations",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pool_id", sa.Integer(), nullable=False),
        sa.Column("vm_id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "ip_address", sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("allocated_at", sa.DateTime(), nullable=False),
        sa.Column("released_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["pool_id"],
            ["ip_pools.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vm_id"],
            ["vms.vm_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "pool_id", "ip_address", "is_active", name="uq_pool_ip_active"
        ),
    )
    op.create_index(
        op.f("ix_ip_allocations_ip_address"),
        "ip_allocations",
        ["ip_address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ip_allocations_is_active"),
        "ip_allocations",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ip_allocations_pool_id"), "ip_allocations", ["pool_id"], unique=False
    )
    op.create_index(
        op.f("ix_ip_allocations_vm_id"), "ip_allocations", ["vm_id"], unique=False
    )
    op.create_index(
        "ix_pool_active", "ip_allocations", ["pool_id", "is_active"], unique=False
    )
    op.create_index(
        "ix_vm_id_active", "ip_allocations", ["vm_id", "is_active"], unique=False
    )
    op.alter_column(
        "vms",
        "name",
        existing_type=sa.VARCHAR(length=100),
        type_=sqlmodel.sql.sqltypes.AutoString(length=64),
        existing_nullable=False,
    )
    # ### end Alembic commands ###

    # Seed default IP pool

    op.execute(
        sa.text("""
            INSERT INTO ip_pools (name, network, cidr, gateway, start_ip, end_ip, is_active, description, created_at, updated_at)
            VALUES (
                'default',
                '172.16.0',
                '172.16.0.0/24',
                '172.16.0.1',
                '172.16.0.2',
                '172.16.0.254',
                true,
                'Default IP pool for VM allocations',
                NOW(),
                NOW()
            )
        """)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vms",
        "name",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=64),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    op.drop_index("ix_vm_id_active", table_name="ip_allocations")
    op.drop_index("ix_pool_active", table_name="ip_allocations")
    op.drop_index(op.f("ix_ip_allocations_vm_id"), table_name="ip_allocations")
    op.drop_index(op.f("ix_ip_allocations_pool_id"), table_name="ip_allocations")
    op.drop_index(op.f("ix_ip_allocations_is_active"), table_name="ip_allocations")
    op.drop_index(op.f("ix_ip_allocations_ip_address"), table_name="ip_allocations")
    op.drop_table("ip_allocations")
    op.drop_index(op.f("ix_ip_pools_name"), table_name="ip_pools")
    op.drop_index(op.f("ix_ip_pools_is_active"), table_name="ip_pools")
    op.drop_table("ip_pools")
    # ### end Alembic commands ###
