"""add vm model

Revision ID: 413818ea977d
Revises: 5f5496bbef36
Create Date: 2026-02-01 09:32:35.988832

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "413818ea977d"
down_revision: Union[str, Sequence[str], None] = "5f5496bbef36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vms",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vm_id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column("vcpu_count", sa.Integer(), nullable=False),
        sa.Column("memory_mb", sa.Integer(), nullable=False),
        sa.Column(
            "ip_address", sqlmodel.sql.sqltypes.AutoString(length=15), nullable=True
        ),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("host", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("kernel_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("rootfs_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vms_ip_address"), "vms", ["ip_address"], unique=False)
    op.create_index(op.f("ix_vms_user_id"), "vms", ["user_id"], unique=False)
    op.create_index(op.f("ix_vms_vm_id"), "vms", ["vm_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vms_vm_id"), table_name="vms")
    op.drop_index(op.f("ix_vms_user_id"), table_name="vms")
    op.drop_index(op.f("ix_vms_ip_address"), table_name="vms")
    op.drop_table("vms")
    # ### end Alembic commands ###
